---
- name: Getting binaries for Gleecs
  hosts: gleecs
  become: yes
  become_method: sudo
  tasks:
  - name: Create directory for gleecs
    file:
      path: "{{ gleecs_dir }}"
      state: directory

  - name: Installing required packages
    apt:
      pkg:
      - build-essential
      - libtool
      - autotools-dev
      - automake
      - pkg-config
      - bsdmainutils
      - python3
      - libssl-dev
      - libevent-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libminiupnpc-dev
      - libzmq3-dev
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      - libqrencode-dev
      - wget

  - name: Preconfiguring node
    script: "{{ script_dir }}/configure_node.sh"

  - name: Downloading latest known release from github
    script: "{{ script_dir }}/download_script.sh {{ gleecs_link }} {{ gleecs_dir }} gleecs"

  - name: Installing gleecs
    script: "{{ script_dir }}/install_gleecs.sh {{ gleecs_dir }}"